import { Reveal_User } from '/support/classes/User'

let User = {}

describe('CLV', function() {
	before(function() {
		cy.fixture('credentials').then(function(data) {
			let shopId = Cypress.env("shopId") || "demo01"
			User = new Reveal_User(data[shopId])
		})
	})

    it('Graph Buttons', function() {
        User.Goto('Customer Lifetime Value')
    // main Discover button
        cy.get('#discover').click()
        cy.get('.collapse-text-title').should('be.visible')
        cy.get('#btn-expand-less').click()
    // Settings Button 
        cy.get('.chart-settings-button > .rv-integrations').click()
        cy.get('#chart-customer_lifetime_value_historical_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .mb-3 > b')
            .should('be.visible')
        cy.get('#chart-customer_lifetime_value_historical_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click()
        cy.wait(500)
    })

    it('Check Discover Button', function() {
        cy.viewport(1300,3000)
    // Revenue Per Customer
        cy.get('#chart-customer_lifetime_value_historical-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click()
        cy.get('.video-tutorial-chart-customer_lifetime_value_historical-timeline-line > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','The Revenue per customer is the historical revenue generated by each of your customers. It is calculated by dividing the total number of revenue generated by the total number of customers that you acquired')
        cy.closeDiscovery()  
    // Revenue per Customer by RFM Group
        cy.get('#chart-customer_lifetime_value_historical_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click()
        cy.get('.video-tutorial-chart-customer_lifetime_value_historical_by_rfm-aggregated-bar > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','The Revenue per customer is the historical revenue generated by each of your customers. It is calculated by dividing the total number of revenue generated by the total number of customers that you acquired')
        cy.closeDiscovery()
    // Revenue per Customer by RFM Group
        cy.get('#chart-customer_lifetime_value_historical_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click()
        cy.get('.video-tutorial-chart-customer_lifetime_value_historical_by_rfm-timeline-line > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','The Revenue per customer is the historical revenue generated by each of your customers. It is calculated by dividing the total number of revenue generated by the total number of customers that you acquired')
        cy.closeDiscovery()   
    // CLV by RFM Groups
        cy.get('#chart-clv_by_rfm_groups-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click()
        cy.closeDiscovery()
    })

    it('Check Zoom Button', function() {
        cy.viewport(1300,3000)
    // Revenue Per Customer
        cy.get('#chart-customer_lifetime_value_historical-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-customer_lifetime_value_historical-timeline-line > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.closeZoom()
        cy.wait(500)
    // Revenue per Customer by RFM Group
        cy.get('#chart-customer_lifetime_value_historical_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-customer_lifetime_value_historical_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.closeZoom()
        cy.wait(500)
    // Revenue per Customer by RFM Group
        cy.get('#chart-customer_lifetime_value_historical_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-customer_lifetime_value_historical_by_rfm-timeline-line > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.closeZoom()
        cy.wait(500)
    // CLV by RFM Groups
        cy.get('#chart-clv_by_rfm_groups-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-clv_by_rfm_groups-aggregated-bar > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.closeZoom()
        cy.wait(500)
    })

    it('Check Tooltips', function() {
        cy.viewport(1300,3000)
    // Predictive CLV [RON]
        cy.get('#chart-customer_lifetime_value_predictive-aggregated-panel > .card > .card-content-panel > .card-content-panel-wrapper > .card-content-panel-title > .rv-btn-info').click()
        cy.tooltip('is the predicted sum')  
    // Revenue per Customer [RON]
        cy.get('#chart-customer_lifetime_value_historical-aggregated-panel > .card > .card-content-panel > .card-content-panel-wrapper > .card-content-panel-title > .rv-btn-info').click()
        cy.tooltip('revenue generated by')
    // Revenue Per Customer
        cy.get('#chart-customer_lifetime_value_historical-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-title > .card-title-chart > .rv-btn-info').click()
        cy.tooltip('timeline')
    // Revenue per Customer by RFM Group
        cy.get('#chart-customer_lifetime_value_historical_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-title > .card-title-chart > .rv-btn-info').click()
        cy.tooltip('aggregated')
    // Revenue per Customer by RFM Group
        cy.get('#chart-customer_lifetime_value_historical_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-title > .card-title-chart > .rv-btn-info').click()
        cy.tooltip('timeline')
    // CLV by RFM Groups
        cy.get('#chart-clv_by_rfm_groups-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-title > .card-title-chart > .rv-btn-info').click()
        cy.tooltip('aggregated')
    })
})