import { Reveal_User } from '/support/classes/User'
import { Reveal_Shop } from '/support/classes/Shop'

let User = {}
let Shop = {}

describe('Segmentation', function() {
	before(function() {
		cy.fixture('credentials').then(function(data) {
			let shopId = Cypress.env("shopId") || "demo01"
			User = new Reveal_User(data[shopId])
            Shop = new Reveal_Shop(data[shopId])
		})
	})

    it('Graph Buttons', function() {
        User.Goto('Segmentation')
    })

    it('Check Discovery Button', function() {
        cy.viewport(1300, 4000)
        cy.wait(500)
    // RFM Segmentation 
        cy.get('#chart-revenue_margin_by_rfm-aggregated-table > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .btn > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-revenue_margin_by_rfm-aggregated-table > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','RFM Segmentation stands for recency, frequency, monetary value. It is used to create customer segments based on buying behaviors.')
        cy.closeDiscovery()
    // Revenue vs. Margin by RFM Group
        cy.get('#chart-revenue_margin_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-revenue_margin_by_rfm-aggregated-bar > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','This card shows you how the revenue and margin are distributed between customer segments. This calculation will show you which customer segments are more valuable to your business.')
        cy.closeDiscovery()
    // NPS per RFM Group 
        cy.get('#chart-nps_score_per_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-nps_score_per_rfm-aggregated-bar > .modal-dialog > .modal-content').should('be.visible')
            .should('contain','This card shows you the NPS score given by your customers')
        cy.closeDiscovery()
    // NPS per RFM Group
        cy.get('#chart-nps_score_per_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-nps_score_per_rfm-timeline-line > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','This card shows you the NPS score given by your customers')
        cy.closeDiscovery()
    // Order Count by RFM Group
        cy.get('#chart-order_count_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-order_count_by_rfm-aggregated-bar > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','This card shows you how many orders have been completed by customers belonging to each customer group')
        cy.closeDiscovery()
    // Order Count by RFM Group
        cy.get('#chart-order_count_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-order_count_by_rfm-timeline-line > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','This card shows you how many orders have been completed by customers belonging to each customer group')
        cy.closeDiscovery()
    // Margin by RFM Group
        cy.get('#chart-margin_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-margin_by_rfm-aggregated-bar > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','This card shows you the margins generated by each of your RFM Groups')
        cy.closeDiscovery()
    // Margin by RFM Group
        cy.get('#chart-margin_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-margin_by_rfm-timeline-line > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','This card shows you the margins generated by each of your RFM Groups')
        cy.closeDiscovery()
    // Customer Count by RFM Group
        cy.get('#chart-customer_count_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-customer_count_by_rfm-aggregated-bar > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','This card shows you the number of customers assigned to each of your RFM groups. This information can help you have a better idea of your customer segments and what are the issues and opportunities with each one.')
        cy.closeDiscovery()
    // Customer Count by RFM Group
        cy.get('#chart-customer_count_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-customer_count_by_rfm-timeline-line > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','This card shows you the number of customers assigned to each of your RFM groups based on your timeline selection. This information can help you have a better idea of your customer segments and what are the issues and opportunities with each one.')
        cy.closeDiscovery()
    // Revenue by RFM Group
        cy.get('#chart-revenue_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-revenue_by_rfm-aggregated-bar > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','This card shows you the revenue generated by each of your RFM Groups.')
        cy.closeDiscovery()
    // Revenue by RFM Group
        cy.get('#chart-revenue_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        cy.get('.video-tutorial-chart-revenue_by_rfm-timeline-line > .modal-dialog > .modal-content > div')
            .should('be.visible').should('contain','This card shows you the revenue generated by each of your RFM Groups based on your timeline selection.')
        cy.closeDiscovery()
    // Order Return Split by RFM Group
        cy.get('#chart-return_split_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .active > .rv-discover').click({force:true})
        if (Shop.isStage()) {
            cy.get('.video-tutorial-chart-return_split_by_rfm-timeline-line > .modal-dialog > .modal-content > div')
                .should('be.visible').should('contain','This card shows the distribution of orders containing returned items, between customers within each of your RFM segments, in the time interval you selected.')
        } else {
            cy.get('.video-tutorial-chart-return_split_by_rfm-timeline-line > .modal-dialog > .modal-content > div')
                .should('be.visible').should('contain','This card shows the distribution of orders placed in the selected time interval, containing returned items, between customers within each of your RFM segments, in the same time interval.')
        }
        cy.closeDiscovery()
    })

    it('Check Zoom Button', function() {
        cy.viewport(1300, 3000)
    // Revenue vs. Margin by RFM Group
        cy.get('#chart-revenue_margin_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-revenue_margin_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.closeZoom()
        cy.wait(1000)
    // NPS per RFM Group 
        cy.get('#chart-nps_score_per_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-nps_score_per_rfm-aggregated-bar > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.get('#closeFullScreen').click({force:true})
        cy.wait(1000)
    // NPS per RFM Group
        cy.get('#chart-nps_score_per_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-nps_score_per_rfm-timeline-line > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.get('#closeFullScreen').click({force:true})
        cy.wait(1000)
    // Order Count by RFM Group
        cy.get('#chart-order_count_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-order_count_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.get('#closeFullScreen').click({force:true})
        cy.wait(1000)
    // Order Count by RFM Group
        cy.get('#chart-order_count_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-order_count_by_rfm-timeline-line > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.get('#closeFullScreen').click({force:true})
        cy.wait(1000)
    // Margin by RFM Group
        cy.get('#chart-margin_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-margin_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')     
        cy.get('#closeFullScreen').click({force:true})     
        cy.wait(1000)
    // Margin by RFM Group
        cy.get('#chart-margin_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-margin_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')    
        cy.get('#closeFullScreen').click({force:true})
        cy.wait(1000)
    // Customer Count by RFM Group
        cy.get('#chart-customer_count_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-customer_count_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.get('#closeFullScreen').click({force:true})
        cy.wait(1000)
    // Customer Count by RFM Group
        cy.get('#chart-customer_count_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-margin_by_rfm-timeline-line > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.get('#closeFullScreen').click({force:true})
        cy.wait(1000)
    // Revenue by RFM Group
        cy.get('#chart-revenue_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-customer_count_by_rfm-timeline-line > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.get('#closeFullScreen').click({force:true})  
        cy.wait(1000) 
    // Revenue by RFM Group
        cy.get('#chart-revenue_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-revenue_by_rfm-timeline-line > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.get('#closeFullScreen').click({force:true})  
        cy.wait(1000) 
    // Order Return Split by RFM Group
        cy.get('#chart-return_split_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .full-screen > .rv-zoom').click({force:true})
        cy.get('#chart-revenue_by_rfm-timeline-line > .card > :nth-child(1) > .chart-container > .main-view')
            .should('be.visible')
        cy.get('#closeFullScreen').click({force:true})
        cy.wait(1000)
    })

    it('Check Settings Button', function() {
        cy.viewport(1300, 3500)
    // Revenue vs. Margin by RFM Group
        cy.get('#chart-revenue_margin_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-revenue_margin_by_rfm-aggregated-bar > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-revenue_margin_by_rfm-aggregated-bar > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    // NPS per RFM Group
        cy.get('#chart-nps_score_per_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-nps_score_per_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-nps_score_per_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    // Order Count by RFM Group
        cy.get('#chart-order_count_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-order_count_by_rfm-aggregated-bar > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-order_count_by_rfm-aggregated-bar > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    // Order Count by RFM Group
        cy.get('#chart-order_count_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-order_count_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-order_count_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    // Margin by RFM Group
        cy.get('#chart-margin_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-margin_by_rfm-aggregated-bar > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-margin_by_rfm-aggregated-bar > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    // Margin by RFM Group
        cy.get('#chart-margin_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-margin_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-margin_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    // Customer Count by RFM Group
        cy.get('#chart-customer_count_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-customer_count_by_rfm-aggregated-bar > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-customer_count_by_rfm-aggregated-bar > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    // Customer Count by RFM Group
        cy.get('#chart-customer_count_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-customer_count_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-customer_count_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    // Revenue by RFM Group
        cy.get('#chart-revenue_by_rfm-aggregated-bar > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-revenue_by_rfm-aggregated-bar > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-revenue_by_rfm-aggregated-bar > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    // Revenue by RFM Group
        cy.get('#chart-revenue_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-revenue_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-revenue_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    // Order Return Split by RFM Group
        cy.get('#chart-return_split_by_rfm-timeline-line > .card > :nth-child(1) > .chart-bar-top > .card-actions > .fake-dropdown > .dropdown-menu > .chart-settings-button > .rv-integrations').click({force:true})
        cy.get('#chart-return_split_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .mb-3')
            .should('be.visible')
        cy.get('#chart-return_split_by_rfm-timeline-line > .modal.card-settings > .modal-dialog > .modal-content > .card-settings > .d-flex > .btn').click({force:true})
        cy.wait(500)
    })
})